language: c
sudo: false
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
before_cache:
- rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
- rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-1.22
    - ghc-7.10.1
  ssh_known_hosts: travispoulsen.com
env:
- - CABALVER=1.22
  - GHCVER=7.10.1
before_install:
  - bash _scripts/pre_install.sh
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
install:
  - bash _scripts/install.sh
script:
  - cabal run build
after_success:
  - bash _scripts/deploy.sh
