language: c

# explicitly request container-based infrastructure
sudo: false


cache:
  directories:
    - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.10.1

env:
  - [CABALVER=1.22, GHCVER=7.10.1]

before_install:
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal sandbox init
  - cabal update
  - cabal install --only-dependencies

script:
  - cabal run build